#!/bin/bash
# Demo: Using the new -o debug option

echo "=============================================="
echo "Demo: Debug Option"
echo "=============================================="
echo ""
echo "The -o debug true option shows:"
echo "  1. Options loaded from config files"
echo "  2. Options passed via CLI"
echo "  3. Final merged options"
echo "  4. Actual API payload being sent"
echo ""
echo "=============================================="
echo ""

# First, show current config
echo "Current config:"
llm 1min options list
echo ""

echo "=============================================="
echo "Example 1: Basic debug output"
echo "=============================================="
echo ""
echo "Command:"
echo "  llm -m 1min/gpt-4o -o debug true \"What is 2+2?\""
echo ""
echo "This will show debug information in stderr (before the response)"
echo ""

echo "=============================================="
echo "Example 2: Debug with web_search enabled"
echo "=============================================="
echo ""
echo "Command:"
echo "  llm -m 1min/gpt-4o -o debug true \"tell me about https://www.sowitty.com\""
echo ""
echo "This will show that web_search is enabled (from config) and"
echo "what parameters are being sent to the API."
echo ""

echo "=============================================="
echo "Example 3: Override web_search via CLI"
echo "=============================================="
echo ""
echo "Command:"
echo "  llm -m 1min/gpt-4o -o debug true -o web_search false \"test\""
echo ""
echo "This will show that web_search is disabled (overridden by CLI)"
echo ""

echo "=============================================="
echo "You can also use the environment variable:"
echo "=============================================="
echo ""
echo "  LLM_1MIN_DEBUG=1 llm -m 1min/gpt-4o \"test\""
echo ""
echo "This is equivalent to using -o debug true"
echo ""

echo "=============================================="
echo "Try it yourself!"
echo "=============================================="
